services:
  laravel:
    restart: unless-stopped
    container_name: weather-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/var/www/html
      - ../storage/app:/var/www/html/storage/app
      - ../database:/var/www/html/database
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    ports:
      - "8080:80"
    networks:
      - n-laravel

networks:
  n-laravel:
    driver: bridge
